//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileSizeCounter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the folder you want to inspect.
        /// </summary>
        internal static string MainWindow_Info_SelectTargetDirectory {
            get {
                return ResourceManager.GetString("MainWindow_Info_SelectTargetDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Size Counter.
        /// </summary>
        internal static string Message_ApplicationTitle {
            get {
                return ResourceManager.GetString("Message_ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file or folder will be deleted permanently (bypassing the recycle bin), are you sure you want to delete it?.
        /// </summary>
        internal static string Message_DeleteFileConfirmMsg {
            get {
                return ResourceManager.GetString("Message_DeleteFileConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete the item &apos;{0}&apos;, please make you have the permission to delete it.
        ///
        ///Detail error information: {1}.
        /// </summary>
        internal static string Message_Error_FailToDeletePrompt {
            get {
                return ResourceManager.GetString("Message_Error_FailToDeletePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory is not valid or does not exist. Only the existing directory could be inspected..
        /// </summary>
        internal static string Message_Error_InspectDirectoryInvalid {
            get {
                return ResourceManager.GetString("Message_Error_InspectDirectoryInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only valid numeric value can be accepted, e.g. 2, 1.5 etc..
        /// </summary>
        internal static string Message_Error_SizeFilterValueInvalid {
            get {
                return ResourceManager.GetString("Message_Error_SizeFilterValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression is not a member access expression..
        /// </summary>
        internal static string PropertySupport_Error_ExpressionIsNotMemberExpression {
            get {
                return ResourceManager.GetString("PropertySupport_Error_ExpressionIsNotMemberExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The member access expression does not access a property..
        /// </summary>
        internal static string PropertySupport_Error_MemberExpressionNotAccessProperty {
            get {
                return ResourceManager.GetString("PropertySupport_Error_MemberExpressionNotAccessProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The referenced property is a static property..
        /// </summary>
        internal static string PropertySupport_Error_PropertyIsStatic {
            get {
                return ResourceManager.GetString("PropertySupport_Error_PropertyIsStatic", resourceCulture);
            }
        }
    }
}
